### ISSUE TITLE
BulkWrite exception: Unexpected DDB type

### ISSUE THREAD

**Issue by briananderton-il** [AllocZero/EfficientDynamoDb#113]
Getting sporadic exceptions when using BulkWrite functionality in parallel like such:

```
var batches = entities.Batch(25);
var tasks = batches.Select(b=>context.BatchWrite().WithItems(b.Select(Batch.PutItem)).ExecuteAsync(ct));
await Task.WhenAll(tasks);
```

Exception:
```
EfficientDynamoDb.Exceptions.DdbException: Unexpected DDB type
   at EfficientDynamoDb.Internal.Reader.DdbJsonReader.ReadCore(Utf8JsonReader& reader, DdbReadStack& state, IParsingOptions options) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\Reader\DdbJsonReader\DdbJsonReader.ReadCore.cs:line 30
   at EfficientDynamoDb.Internal.Reader.DdbJsonReader.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, DdbReadStack& readStack, IParsingOptions options) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\Reader\DdbJsonReader\DdbJsonReader.ReadCore.cs:line 12
   at EfficientDynamoDb.Internal.Reader.DdbJsonReader.ReadAsync(Stream utf8Json, IParsingOptions options, Boolean returnCrc, CancellationToken cancellationToken) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\Reader\DdbJsonReader.cs:line 59
   at EfficientDynamoDb.DynamoDbLowLevelContext.ReadDocumentAsync(HttpResponseMessage response, IParsingOptions options, CancellationToken cancellationToken) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\DynamoDbLowLevelContext.cs:line 206
   at EfficientDynamoDb.DynamoDbLowLevelContext.ReadDocumentAsync(HttpResponseMessage response, IParsingOptions options, CancellationToken cancellationToken) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\DynamoDbLowLevelContext.cs:line 211
   at EfficientDynamoDb.DynamoDbContext.BatchWriteItemAsync(BuilderNode node, CancellationToken cancellationToken) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\DynamoDbContext\DynamoDbContext,BatchWriteItem.cs:line 19
```

**Comment by lezzi** [comment]
Thank you for reporting the bug. Sporadic behavior was related to table throttling and `UnprocessedItems` parsing. It has been addressed in the [0.9.1-alpha.0.17](https://www.nuget.org/packages/EfficientDynamoDb/0.9.1-alpha.0.17).

We plan to release the stable **0.9.1** at Monday/Tuesday.

**Comment by briananderton-il** [comment]
Thanks - unfortunately still getting the same exception, although perhaps taking a bit longer (25% of 100k items) to reproduce.

**Comment by lezzi** [comment]
@briananderton-il sorry to hear that. I am currently getting a different exception which is expected. May I ask you to share the full stack trace again and double-check that you are using the latest version?

**Comment by briananderton-il** [comment]
@lezzi - I wrote a simple console app to repro the issue.  Note that the code purposely writes to a limited number of partitions, and utilizes a table set to OnDemand capacity.  It directly links to the downloaded latest master branch of the code in order to get full stack trace line numbers.  In this repro, I get the _Unexpected DDB Type_ exception usually during the cleanup/delete stage of the code.   And I get a separate DdbException wrapping an unhandled BadFormat error type: _com.amazon.coral.availability#ThrottlingException_. (after many other correctly handled ProvisionedThroughputExceeded errors).  I assume this error should also use one of the retry strategies.

Copied below are the exceptions, and Program.cs from the repro app.

```
EfficientDynamoDb.Exceptions.DdbException: Unexpected DDB type
   at EfficientDynamoDb.Internal.Reader.DdbJsonReader.ReadCore(Utf8JsonReader& reader, DdbReadStack& state, IParsingOptions options) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\Reader\DdbJsonReader\DdbJsonReader.ReadCore.cs:line 30
   at EfficientDynamoDb.Internal.Reader.DdbJsonReader.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, DdbReadStack& readStack, IParsingOptions options) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\Reader\DdbJsonReader\DdbJsonReader.ReadCore.cs:line 12
   at EfficientDynamoDb.Internal.Reader.DdbJsonReader.ReadAsync(Stream utf8Json, IParsingOptions options, Boolean returnCrc, CancellationToken cancellationToken) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\Reader\DdbJsonReader.cs:line 59
   at EfficientDynamoDb.DynamoDbLowLevelContext.ReadDocumentAsync(HttpResponseMessage response, IParsingOptions options, CancellationToken cancellationToken) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\DynamoDbLowLevelContext.cs:line 206
   at EfficientDynamoDb.DynamoDbLowLevelContext.ReadDocumentAsync(HttpResponseMessage response, IParsingOptions options, CancellationToken cancellationToken) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\DynamoDbLowLevelContext.cs:line 211
   at EfficientDynamoDb.DynamoDbContext.BatchWriteItemAsync(BuilderNode node, CancellationToken cancellationToken) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\DynamoDbContext\DynamoDbContext,BatchWriteItem.cs:line 19
   at ConsoleApp7.Program.Main(String[] args) in C:\Users\user\source\repos\ConsoleApp7\ConsoleApp7\Program.cs:line 28
   at ConsoleApp7.Program.Main(String[] args) in C:\Users\user\source\repos\ConsoleApp7\ConsoleApp7\Program.cs:line 25
```

```
EfficientDynamoDb.Exceptions.DdbException: [com.amazon.coral.availability#ThrottlingException] Throughput exceeds the current capacity of your table or index. DynamoDB is automatically scaling your table or index so please try again shortly. If exceptions persist, check if you have a hot key: https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/bp-partition-key-design.html
   at EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\ErrorHandler.cs:line 48
   at EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\ErrorHandler.cs:line 76
   at EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\ErrorHandler.cs:line 76
   at EfficientDynamoDb.Internal.HttpApi.SendAsync(DynamoDbContextConfig config, HttpContent httpContent, CancellationToken cancellationToken) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\HttpApi.cs:line 55
   at EfficientDynamoDb.DynamoDbContext.BatchWriteItemAsync(BuilderNode node, CancellationToken cancellationToken) in C:\Users\user\source\repos\ConsoleApp7\EfficientDynamoDb-master\src\EfficientDynamoDb\DynamoDbContext\DynamoDbContext,BatchWriteItem.cs:line 34
   at ConsoleApp7.Program.Main(String[] args) in C:\Users\user\source\repos\ConsoleApp7\ConsoleApp7\Program.cs:line 35
```

```
using System;
using System.Linq;
using System.Threading.Tasks;
using EfficientDynamoDb;
using EfficientDynamoDb.Attributes;
using EfficientDynamoDb.Configs;
using EfficientDynamoDb.Configs.Retries;
using MoreLinq;

namespace ConsoleApp7
{
	class Program
	{
		static async Task Main(string[] args)
		{
			try
			{
				Console.WriteLine("START");
				var credentials = new AwsCredentials(...);
				var config = new DynamoDbContextConfig(..., credentials);
				config.RetryStrategies.ProvisionedThroughputExceededStrategy = new FixedRetryStrategy(50, int.MaxValue);
				var context = new DynamoDbContext(config);

				// delete previous entities
				await foreach (var scan in context.Scan<Entity>().ToAsyncEnumerable())
				{
					var deletes = scan.Batch(25).Select(b=>context.BatchWrite().WithItems(b.Select(e=>Batch.DeleteItem<Entity>().WithPrimaryKey(e.Pk, e.Sk))).ExecuteAsync());
					await Task.WhenAll(deletes);
				}
				Console.WriteLine("Finished deletes");

				// add new entities
				var entities = Enumerable.Range(0, 10000).Select(i => new Entity { Pk = (i % 10).ToString(), Sk = i.ToString() }); // 10 shards
				var puts = entities.Batch(25).Select(b=>context.BatchWrite().WithItems(b.Select(Batch.PutItem)).ExecuteAsync());
				await Task.WhenAll(puts);
				Console.WriteLine("Finished puts");

				Console.WriteLine("DONE");
			}
			catch (Exception e)
			{
				Console.WriteLine(e);
			}
		}
	}

	[DynamoDbTable(...)]
	public class Entity
	{
		[DynamoDbProperty("Pk", DynamoDbAttributeType.PartitionKey)] public string Pk { get; set; }
		[DynamoDbProperty("Sk", DynamoDbAttributeType.SortKey)] public string Sk { get; set; }
	}

	public class FixedRetryStrategy : IRetryStrategy
	{
		private readonly int _delayMs;
		private readonly int _maxRetries;

		public FixedRetryStrategy(int delayMs, int maxRetries)
		{
			_delayMs = delayMs;
			_maxRetries = maxRetries;
		}

		public bool TryGetRetryDelay(int attempt, out TimeSpan delay)
		{
			Console.WriteLine($"retrying attempt: {attempt}");
			delay = TimeSpan.FromMilliseconds(_delayMs);
			return attempt < _maxRetries;
		}
	}
}
```

**Comment by lezzi** [comment]
Thank you for the awesome repro example 👍 

I think I already know why the batch delete fails and I will definitely check out tonight the second throttling exception. Will get back to you when both are addressed, tested, and merged.

**Comment by lezzi** [comment]
The fix for "Unexpected DDB type" has been merged, it was affecting batch delete operations.

Regarding the `ThrottlingException` - I also pushed the improvement related to errors parsing in general. @briananderton-il you may need to update your app to also use a custom `ThrottlingStrategy`.

The latest nuget version is [0.9.1-alpha.0.19](https://www.nuget.org/packages/EfficientDynamoDb/0.9.1-alpha.0.19)

**Comment by briananderton-il** [comment]
Running better, thanks.   But I am getting one other exception pretty consistently during the delete phase, a DdbException with empty message, during the throttling.  It appears to be another unhandled error type on the HttpStatusCode.BadRequest: _SerializationException_

```
EfficientDynamoDb.Exceptions.DdbException:
   at EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\ErrorHandler.cs:line 53
   at EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\ErrorHandler.cs:line 81
   at EfficientDynamoDb.Internal.ErrorHandler.ProcessErrorAsync(DynamoDbContextMetadata metadata, HttpResponseMessage response, CancellationToken cancellationToken) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\ErrorHandler.cs:line 81
   at EfficientDynamoDb.Internal.HttpApi.SendAsync(DynamoDbContextConfig config, HttpContent httpContent, CancellationToken cancellationToken) in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\Internal\HttpApi.cs:line 55
   at EfficientDynamoDb.DynamoDbContext.ScanAsyncEnumerable[TEntity](String tableName, BuilderNode node, CancellationToken cancellationToken)+MoveNext() in C:\ILE\universal-roster\EfficientDynamoDb-master\src\EfficientDynamoDb\DynamoDbContext\DynamoDbContext.Scan.cs:line 36
   at EfficientDynamoDb.DynamoDbContext.ScanAsyncEnumerable[TEntity](String tableName, BuilderNode node, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
```

**Comment by lezzi** [comment]
Yeah, it was consistently reproducible using the scan. The pagination token was written incorrectly, should be fine now.

**Comment by lezzi** [comment]
Hey @briananderton-il , just wanted to check in with you if there is anything left blocking you or I can close the issue

**Comment by briananderton-il** [comment]
Everything is working much better, thank you!

**Comment by lezzi** [comment]
Closing the issue then, feel free to create a new one if anything else pops up.
